version: "3"
services:
  backend_test:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/home/app/backend/
      - /home/app/backend/node_modules
    command: node_modules/.bin/nodemon --exec npm run test:unit
    ports:
      - 3001:3000
    depends_on:
      - mongodb
    container_name: todo_backend_teste
    env_file:
      - .env-test
    networks:
      - test
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - test
networks:
  test:
    driver: bridge