version: "3"
services:
  backend:
    build:
      dockerfile: Dockerfile
      context: .
    command: node_modules/.bin/nodemon --exec npm test
      - 3001:3000
    depends_on:
      - mongodb
    container_name: todo_backend_test
    env_file:
      - .env-test
    networks:
      - test
  mongodb:
    image: mongo
    ports:
      - 27000:27017
    container_name: mongo_test
    networks:
      - test
networks:
  test:
    driver: bridge